"""ARGUS Reliability Recommendation Engine (Phase 10 §38–§43, §81).

Produces advisory recommendations from current evidence, validated knowledge and
historical outcomes. The rules that shape it:

* **A recommendation cites its sources or it is not created.** ``knowledge_ids``
  and ``experience_ids`` are populated from rows that exist, and
  ``current_evidence`` names the incident, component and observed signals. No
  recommendation is written with an empty evidence record.
* **It never executes.** The strongest thing a recommendation carries is
  :func:`policy_note_for`: what Phase 9 *would* demand if a human chose to act.
  §42 asks for that note explicitly, and it is generated by reading the same
  policy and registry the executor would use — not by restating a guess.
* **Uncertainty travels with the claim** (§40). ``limitations`` always includes
  the sample size behind any historical claim, and the ranking criteria are
  stored in ``ranking`` rather than left implicit.
* **Being wrong is learnable** (§43). ``decide`` and ``record_outcome`` are
  separate: "the engineer accepted it" and "it worked" are different facts, and
  the second is what the learning loop feeds on.
"""

from __future__ import annotations

import hashlib
import logging
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from typing import Any, Optional, Sequence

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import Settings, get_settings
from app.models.intelligence import (
    ComponentReliabilityProfile,
    KnowledgeConfidence,
    KnowledgeStatus,
    KnowledgeType,
    RecommendationOutcome,
    RecommendationStatus,
    RecommendationType,
    ReliabilityKnowledge,
    ReliabilityRecommendation,
)
from app.models.remediation import RemediationActionType
from app.services.experience_retrieval import (
    ExperienceRetrievalService,
    NO_HISTORY_MESSAGE,
    RetrievalResult,
)
from app.services.intelligence_state import (
    RECOMMENDATION_VERDICTS,
    assert_recommendation_transition,
    recommendation_status_for_verdict,
)
from app.services.learning_signatures import FailureSignature

logger = logging.getLogger(__name__)

#: Recommendation type → the Phase 9 action a person would consider. Used only to
#: describe what policy would require; nothing here creates an action.
IMPLIED_ACTIONS: dict[RecommendationType, RemediationActionType] = {
    RecommendationType.CONSIDER_RESTART: RemediationActionType.RESTART_SERVICE,
    RecommendationType.CONSIDER_ROLLBACK: RemediationActionType.ROLLBACK_DEPLOYMENT,
    RecommendationType.CONSIDER_TRAFFIC_SHIFT: (
        RemediationActionType.ROUTE_TRAFFIC_TO_HEALTHY_INSTANCE
    ),
    RecommendationType.REVIEW_CAPACITY: RemediationActionType.SCALE_SERVICE_WITHIN_LIMIT,
    RecommendationType.REVIEW_CONFIGURATION: (
        RemediationActionType.ROLLBACK_CONFIGURATION
    ),
}

#: Ranking weights (§41). Shown in ``ranking`` on every recommendation so the
#: ordering is inspectable rather than mysterious.
RANKING_WEIGHTS: dict[str, float] = {
    "evidence_strength": 0.3,
    "historical_effectiveness": 0.3,
    "current_relevance": 0.25,
    "reversibility": 0.15,
}


@dataclass
class RecommendationDraft:
    """An assembled recommendation, before it is persisted."""

    project_id: uuid.UUID
    recommendation_type: RecommendationType
    title: str
    rationale: str
    current_evidence: dict[str, Any]
    knowledge_ids: list[str] = field(default_factory=list)
    experience_ids: list[str] = field(default_factory=list)
    limitations: list[str] = field(default_factory=list)
    ranking: dict[str, Any] = field(default_factory=dict)
    historical: dict[str, Any] = field(default_factory=dict)
    confidence: KnowledgeConfidence = KnowledgeConfidence.UNKNOWN
    environment_id: Optional[uuid.UUID] = None
    component_id: Optional[uuid.UUID] = None
    incident_id: Optional[uuid.UUID] = None
    forecast_id: Optional[uuid.UUID] = None
    policy_note: Optional[str] = None

    def fingerprint(self) -> str:
        """Identity for deduplication: the same advice about the same subject."""
        payload = "|".join(
            [
                self.recommendation_type.value,
                str(self.incident_id or "-"),
                str(self.component_id or "-"),
                self.title,
            ]
        )
        return hashlib.sha256(payload.encode("utf-8")).hexdigest()


@dataclass
class RankedRecommendation:
    """A draft plus the score that ordered it."""

    draft: RecommendationDraft
    score: float
    criteria: dict[str, float]


class ReliabilityRecommendationEngine:
    """Builds, ranks, persists and closes out recommendations."""

    def __init__(
        self,
        settings: Optional[Settings] = None,
        retrieval: Optional[ExperienceRetrievalService] = None,
    ) -> None:
        self.settings = settings or get_settings()
        self.retrieval = retrieval or ExperienceRetrievalService(self.settings)

    # -- generation -------------------------------------------------------
    async def recommend_for_incident(
        self,
        session: AsyncSession,
        *,
        project_id: uuid.UUID,
        incident_id: uuid.UUID,
        cutoff: Optional[datetime] = None,
    ) -> list[RankedRecommendation]:
        """Every recommendation current evidence supports for one incident."""
        from app.models.incident import Incident
        from app.models.system import SystemComponent
        from app.services.experience_builder import build_current_signature

        incident = await session.get(Incident, incident_id)
        if incident is None or incident.project_id != project_id:
            return []

        signature, reason = await build_current_signature(
            session, incident_id=incident_id, as_of=cutoff
        )
        if signature is None:
            logger.debug("no signature for incident %s: %s", incident_id, reason)
            return []

        component = (
            await session.get(SystemComponent, incident.primary_component_id)
            if incident.primary_component_id
            else None
        )
        retrieval = await self.retrieval.retrieve_for_incident(
            session,
            incident_id=incident_id,
            project_id=project_id,
            cutoff=cutoff,
        )
        knowledge = await self._knowledge_for(
            session,
            project_id=project_id,
            component_id=incident.primary_component_id,
            failure_label=signature.label(),
        )
        drafts = await self._drafts_from_incident(
            session=session,
            incident=incident,
            component=component,
            signature=signature,
            retrieval=retrieval,
            knowledge=knowledge,
        )
        return self.rank(drafts)

    async def recommend_for_component(
        self,
        session: AsyncSession,
        *,
        project_id: uuid.UUID,
        component_id: uuid.UUID,
    ) -> list[RankedRecommendation]:
        """Recommendations for a component with no specific incident (§22)."""
        profile = await session.scalar(
            select(ComponentReliabilityProfile)
            .where(ComponentReliabilityProfile.project_id == project_id)
            .where(ComponentReliabilityProfile.component_id == component_id)
            .order_by(ComponentReliabilityProfile.window_days.desc())
            .limit(1)
        )
        if profile is None or not profile.chronic_signal:
            return []

        knowledge_rows = await self._knowledge_for(
            session,
            project_id=project_id,
            component_id=component_id,
            failure_label=None,
        )
        reasons = list(profile.chronic_reasons or [])
        draft = RecommendationDraft(
            project_id=project_id,
            component_id=component_id,
            recommendation_type=RecommendationType.INVESTIGATE_COMPONENT,
            title="Investigate a chronically unreliable component",
            rationale=(
                f"Over the last {profile.window_days} days this component produced "
                f"{profile.incident_count} incidents, {profile.anomaly_count} anomalies and "
                f"{profile.remediation_count} remediations. Reasons: {'; '.join(reasons)}. "
                f"This recommends investigation; ARGUS does not act on the component."
            ),
            current_evidence={
                "source": "component_profile",
                "profile_id": str(profile.id),
                "window_days": profile.window_days,
                "incident_count": profile.incident_count,
                "anomaly_count": profile.anomaly_count,
                "remediation_count": profile.remediation_count,
                "rollback_count": profile.rollback_count,
                "regression_count": profile.regression_count,
                "mean_recovery_seconds": profile.mean_recovery_seconds,
                "chronic_reasons": reasons,
            },
            knowledge_ids=[str(row.id) for row in knowledge_rows],
            limitations=[
                "Counts reflect what was ingested; a component with sparse telemetry can look quiet.",
                "A chronic signal identifies a pattern of behaviour, not a fault to fix.",
            ],
            confidence=(
                KnowledgeConfidence.MEDIUM
                if knowledge_rows
                else KnowledgeConfidence.LOW
            ),
        )
        return self.rank([draft])

    async def _drafts_from_incident(
        self,
        *,
        session: AsyncSession,
        incident: Any,
        component: Any,
        signature: FailureSignature,
        retrieval: RetrievalResult,
        knowledge: Sequence[ReliabilityKnowledge],
    ) -> list[RecommendationDraft]:
        drafts: list[RecommendationDraft] = []
        base_evidence = {
            "incident_id": str(incident.id),
            "incident_status": getattr(incident.status, "value", str(incident.status)),
            "severity": getattr(incident.severity, "value", str(incident.severity)),
            "component_id": str(component.id) if component is not None else None,
            "component_name": getattr(component, "name", None),
            "failure_signature": signature.label(),
            "anomaly_types": list(signature.anomaly_types),
            "metric_behaviors": list(signature.metric_behaviors),
            "dependency_conditions": list(signature.dependency_conditions),
            "deployment_context": list(signature.deployment_context),
            "resource_pressure": list(signature.resource_pressure),
            "health_state": signature.health_state,
        }
        historical = {
            "comparable_episodes": len(retrieval.matches),
            "successful_resolutions": retrieval.success_count,
            "summary": retrieval.summary,
            "observed_patterns": [
                {
                    "action_types": (match.resolution or {}).get("action_types", []),
                    "outcome": match.outcome,
                }
                for match in retrieval.matches[:10]
            ],
        }
        experience_ids = [match.experience_id for match in retrieval.matches]
        knowledge_ids = [str(row.id) for row in knowledge]
        sample = len(retrieval.matches)
        sample_note = (
            f"Based on {sample} comparable historical episode(s)."
            if sample
            else NO_HISTORY_MESSAGE
        )
        small_sample_note = (
            f"Only {sample} comparable episode(s) — too few to describe a pattern."
            if 0 < sample < self.settings.INTELLIGENCE_MIN_EFFECTIVENESS_SAMPLES
            else None
        )

        # -- remediation history suggests an action (§39, §42)
        action_counts, success_counts = _action_tallies(retrieval)
        for action, count in sorted(action_counts.items(), key=lambda item: -item[1]):
            successes = success_counts.get(action, 0)
            rec_type = _recommendation_for_action(action)
            if rec_type is None:
                continue
            failures = count - successes
            drafts.append(
                RecommendationDraft(
                    project_id=incident.project_id,
                    environment_id=incident.environment_id,
                    component_id=incident.primary_component_id,
                    incident_id=incident.id,
                    recommendation_type=rec_type,
                    title=f"Consider {action.replace('_', ' ').lower()} for this incident",
                    rationale=(
                        f"{action.upper()} has historically resolved {successes} of {count} "
                        f"comparable episodes; {failures} did not resolve as a success. {sample_note}"
                    ),
                    current_evidence=base_evidence,
                    knowledge_ids=[
                        str(row.id)
                        for row in knowledge
                        if action.lower() in (row.feature_signature or "").lower()
                    ],
                    experience_ids=experience_ids,
                    limitations=[
                        "Historical outcomes describe past episodes; they do not guarantee this one.",
                        *([small_sample_note] if small_sample_note else []),
                        "Acting on this still requires Phase 9 policy, safety and (usually) approval.",
                    ],
                    historical=historical,
                    confidence=_confidence_for(sample, successes, self.settings),
                    policy_note=await self._policy_note(session, incident, rec_type),
                    ranking={"sample_size": sample},
                )
            )

        # -- regression or rollback in the same incident's history (§39)
        rolled_back = [
            match
            for match in retrieval.matches
            if (match.resolution or {}).get("rollback_performed")
        ]
        if rolled_back:
            drafts.append(
                RecommendationDraft(
                    project_id=incident.project_id,
                    environment_id=incident.environment_id,
                    component_id=incident.primary_component_id,
                    incident_id=incident.id,
                    recommendation_type=RecommendationType.REVIEW_REMEDIATION,
                    title="Review a remediation that had to be rolled back",
                    rationale=(
                        f"{len(rolled_back)} comparable episode(s) were escalated, executed and then "
                        f"rolled back. The remediation path for this failure signature is worth "
                        f"reviewing before it is attempted again."
                    ),
                    current_evidence=base_evidence,
                    knowledge_ids=knowledge_ids,
                    experience_ids=[match.experience_id for match in rolled_back],
                    limitations=[
                        "A rollback is not proof the action was wrong — it may have been precautionary.",
                    ],
                    historical=historical,
                    confidence=KnowledgeConfidence.LOW,
                    policy_note=await self._policy_note(
                        session, incident, RecommendationType.REVIEW_REMEDIATION
                    ),
                )
            )

        # -- current context: dependency, deployment, capacity, configuration
        if signature.dependency_conditions:
            drafts.append(
                _context_draft(
                    incident=incident,
                    evidence=base_evidence,
                    knowledge_ids=knowledge_ids,
                    experience_ids=experience_ids,
                    historical=historical,
                    recommendation_type=RecommendationType.INVESTIGATE_DEPENDENCY,
                    title="Investigate a dependency that was degraded at the time",
                    rationale=(
                        f"The failure context includes {', '.join(signature.dependency_conditions)}. "
                        f"A dependency condition is part of the observed situation, not proof of cause."
                    ),
                )
            )
        if signature.deployment_context:
            drafts.append(
                _context_draft(
                    incident=incident,
                    evidence=base_evidence,
                    knowledge_ids=knowledge_ids,
                    experience_ids=experience_ids,
                    historical=historical,
                    recommendation_type=RecommendationType.REVIEW_RECENT_CHANGE,
                    title="Review the recent change that preceded this incident",
                    rationale=(
                        f"The failure context includes {', '.join(signature.deployment_context)}. "
                        f"Proximity is temporal; this recommends a look, not a rollback."
                    ),
                )
            )
        if signature.resource_pressure:
            drafts.append(
                _context_draft(
                    incident=incident,
                    evidence=base_evidence,
                    knowledge_ids=knowledge_ids,
                    experience_ids=experience_ids,
                    historical=historical,
                    recommendation_type=RecommendationType.REVIEW_CAPACITY,
                    title="Review capacity: resource pressure was observed",
                    rationale=(
                        f"The failure context includes {', '.join(signature.resource_pressure)}. "
                        f"Capacity changes have their own limits under Phase 9 policy."
                    ),
                )
            )

        #: §42. A context recommendation may still imply an action (capacity
        #: review suggests scaling), so the policy note is filled from the same
        #: resolver the executor uses rather than left blank.
        for draft in drafts:
            if (
                draft.policy_note is None
                and draft.recommendation_type in IMPLIED_ACTIONS
            ):
                draft.policy_note = await self._policy_note(
                    session, incident, draft.recommendation_type
                )

        # -- no history at all: say so, and recommend investigation only
        if not retrieval.matches:
            drafts.append(
                RecommendationDraft(
                    project_id=incident.project_id,
                    environment_id=incident.environment_id,
                    component_id=incident.primary_component_id,
                    incident_id=incident.id,
                    recommendation_type=RecommendationType.INVESTIGATE_COMPONENT,
                    title="Investigate this failure — no comparable history exists",
                    rationale=(
                        f"{NO_HISTORY_MESSAGE} The recommendation is limited to investigation, "
                        f"because ARGUS has nothing to base an action on."
                    ),
                    current_evidence=base_evidence,
                    knowledge_ids=knowledge_ids,
                    experience_ids=[],
                    limitations=[
                        NO_HISTORY_MESSAGE,
                        "No action is recommended on the basis of no evidence.",
                    ],
                    historical=historical,
                    confidence=KnowledgeConfidence.UNKNOWN,
                )
            )
        return drafts

    async def _knowledge_for(
        self,
        session: AsyncSession,
        *,
        project_id: uuid.UUID,
        component_id: Optional[uuid.UUID],
        failure_label: Optional[str],
    ) -> list[ReliabilityKnowledge]:
        """Validated or active knowledge that may inform a recommendation (§4)."""
        stmt = (
            select(ReliabilityKnowledge)
            .where(ReliabilityKnowledge.project_id == project_id)
            .where(
                ReliabilityKnowledge.status.in_(
                    [KnowledgeStatus.VALIDATED, KnowledgeStatus.ACTIVE]
                )
            )
            .order_by(ReliabilityKnowledge.confidence.desc())
            .limit(50)
        )
        rows = list((await session.scalars(stmt)).all())
        filtered = []
        for row in rows:
            if row.component_id is not None and component_id is not None:
                if row.component_id != component_id:
                    continue
            if failure_label and row.knowledge_type == KnowledgeType.FAILURE_PATTERN:
                details = (row.validation or {}).get("details") or {}
                label = details.get("label")
                if label and label != failure_label:
                    continue
            filtered.append(row)
        return filtered

    async def _policy_note(
        self,
        session: AsyncSession,
        incident: Any,
        rec_type: RecommendationType,
    ) -> Optional[str]:
        """What Phase 9 would require if a human acted on this (§42)."""
        action_type = IMPLIED_ACTIONS.get(rec_type)
        if action_type is None:
            return (
                "No remediation action is implied by this recommendation; acting on it "
                "means investigating, not executing."
            )
        try:
            from app.services.remediation_policy import resolve_policy
            from app.services.remediation_registry import (
                definition_requires_human_approval,
                get_definition,
            )

            policy = await resolve_policy(
                session, incident.project_id, incident.environment_id
            )
            definition = get_definition(action_type)
        except Exception:  # pragma: no cover - policy must never break advice
            logger.warning("could not resolve policy for recommendation", exc_info=True)
            return (
                "Policy could not be resolved; treat any action as requiring approval."
            )

        if policy.emergency_stop_active:
            return (
                "Emergency stop is engaged: Phase 9 would refuse this action "
                f"({policy.emergency_stop_reason or 'no reason recorded'})."
            )
        if policy.allowed_action_types is not None and (
            action_type.value not in policy.allowed_action_types
        ):
            return (
                f"Phase 9 policy does not allow {action_type.value} in this scope; acting on "
                f"this recommendation would be refused."
            )
        if definition_requires_human_approval(definition):
            return f"{action_type.value} requires human approval under Phase 9."
        if policy.execution_mode.value in ("OBSERVE_ONLY",):
            return "Phase 9 is in OBSERVE_ONLY mode: no action would be executed."
        if policy.execution_mode.value == "DRY_RUN":
            return "Phase 9 is in DRY_RUN mode: an attempt would be recorded but not executed."
        if policy.execution_mode.value == "AUTONOMOUS":
            return (
                f"{action_type.value} could be executed autonomously in this scope if it "
                f"passes safety, blast-radius and budget checks."
            )
        return (
            f"{action_type.value} would require human approval "
            f"({policy.execution_mode.value} regime)."
        )

    # -- ranking and persistence ------------------------------------------
    def rank(self, drafts: Sequence[RecommendationDraft]) -> list[RankedRecommendation]:
        """Order drafts by the explicit §41 criteria, highest first."""
        ranked: list[RankedRecommendation] = []
        for draft in drafts:
            criteria = self.score(draft)
            score = sum(
                criteria[name] * weight for name, weight in RANKING_WEIGHTS.items()
            )
            draft.ranking = {
                **draft.ranking,
                "criteria": criteria,
                "weights": dict(RANKING_WEIGHTS),
            }
            ranked.append(
                RankedRecommendation(draft=draft, score=score, criteria=criteria)
            )
        ranked.sort(key=lambda item: (-item.score, item.draft.title))
        return ranked

    def score(self, draft: RecommendationDraft) -> dict[str, float]:
        """The criteria behind the ordering, each on a 0–1 scale (§41)."""
        evidence = _confidence_score(draft.confidence)
        sample = int(draft.ranking.get("sample_size") or 0)
        effective = (
            draft.historical.get("successful_resolutions", 0) / sample
            if sample
            else 0.0
        )
        relevance = 1.0 if draft.incident_id is not None else 0.6
        reversibility = 1.0 if draft.recommendation_type in _REVERSIBLE_TYPES else 0.4
        return {
            "evidence_strength": round(evidence, 4),
            "historical_effectiveness": round(effective, 4),
            "current_relevance": relevance,
            "reversibility": reversibility,
        }

    async def persist(
        self,
        session: AsyncSession,
        draft: RecommendationDraft,
        *,
        now: Optional[datetime] = None,
    ) -> ReliabilityRecommendation:
        """Store a draft, or refresh the open one it duplicates.

        Two runs seeing the same situation must not produce two cards for the same
        advice: the fingerprint of an OPEN recommendation is looked up first, and a
        match is updated in place.
        """
        moment = now or datetime.now(timezone.utc)
        fingerprint = draft.fingerprint()
        existing = await session.scalar(
            select(ReliabilityRecommendation)
            .where(ReliabilityRecommendation.project_id == draft.project_id)
            .where(ReliabilityRecommendation.fingerprint == fingerprint)
            .where(ReliabilityRecommendation.status == RecommendationStatus.OPEN)
            .order_by(ReliabilityRecommendation.created_at.desc())
            .limit(1)
        )
        if existing is not None:
            existing.rationale = draft.rationale
            existing.current_evidence = draft.current_evidence
            existing.knowledge_ids = draft.knowledge_ids
            existing.experience_ids = draft.experience_ids
            existing.limitations = draft.limitations
            existing.ranking = draft.ranking
            existing.historical = draft.historical
            existing.confidence = draft.confidence
            existing.policy_note = draft.policy_note
            await session.flush()
            return existing

        row = ReliabilityRecommendation(
            project_id=draft.project_id,
            environment_id=draft.environment_id,
            component_id=draft.component_id,
            incident_id=draft.incident_id,
            forecast_id=draft.forecast_id,
            recommendation_type=draft.recommendation_type,
            status=RecommendationStatus.OPEN,
            title=draft.title,
            rationale=draft.rationale,
            knowledge_ids=draft.knowledge_ids,
            experience_ids=draft.experience_ids,
            current_evidence=draft.current_evidence,
            limitations=draft.limitations,
            ranking=draft.ranking,
            policy_note=draft.policy_note,
            historical=draft.historical,
            confidence=draft.confidence,
            fingerprint=fingerprint,
            expires_at=moment
            + timedelta(seconds=self.settings.INTELLIGENCE_RECOMMENDATION_TTL_SECONDS),
        )
        session.add(row)
        await session.flush()
        return row

    async def persist_many(
        self,
        session: AsyncSession,
        ranked: Sequence[RankedRecommendation],
        *,
        now: Optional[datetime] = None,
    ) -> list[ReliabilityRecommendation]:
        return [await self.persist(session, item.draft, now=now) for item in ranked]

    # -- decisions and outcomes (§43, §81) --------------------------------
    async def decide(
        self,
        session: AsyncSession,
        recommendation: ReliabilityRecommendation,
        *,
        decision: str,
        actor: str,
        reason: Optional[str] = None,
        now: Optional[datetime] = None,
    ) -> ReliabilityRecommendation:
        """Record that a person accepted or dismissed a recommendation.

        Acceptance is *not* a success claim; the outcome is recorded separately
        (§81), and the status stays ACCEPTED until an outcome verdict arrives.
        """
        moment = now or datetime.now(timezone.utc)
        target = {
            "ACCEPTED": RecommendationStatus.ACCEPTED,
            "DISMISSED": RecommendationStatus.DISMISSED,
        }.get(decision.upper())
        if target is None:
            raise ValueError("decision must be ACCEPTED or DISMISSED")
        assert_recommendation_transition(recommendation.status, target)
        recommendation.status = target
        recommendation.decision = {
            "decision": decision.upper(),
            "actor": actor,
            "reason": reason,
            "at": moment.isoformat(),
        }
        recommendation.decided_by = actor
        recommendation.decided_at = moment
        await session.flush()
        return recommendation

    async def record_outcome(
        self,
        session: AsyncSession,
        recommendation: ReliabilityRecommendation,
        *,
        verdict: str,
        recorded_by: str,
        detail: Optional[dict[str, Any]] = None,
        remediation_action_id: Optional[uuid.UUID] = None,
        incident_id: Optional[uuid.UUID] = None,
        now: Optional[datetime] = None,
    ) -> RecommendationOutcome:
        """Record what actually happened — the fact the learning loop needs (§43)."""
        moment = now or datetime.now(timezone.utc)
        normalized = verdict.upper()
        if normalized not in RECOMMENDATION_VERDICTS:
            raise ValueError(
                f"verdict must be one of {sorted(RECOMMENDATION_VERDICTS)}"
            )
        outcome = RecommendationOutcome(
            project_id=recommendation.project_id,
            recommendation_id=recommendation.id,
            verdict=normalized,
            remediation_action_id=remediation_action_id,
            incident_id=incident_id or recommendation.incident_id,
            detail=detail or {},
            recorded_at=moment,
            recorded_by=recorded_by,
        )
        session.add(outcome)

        target = recommendation_status_for_verdict(normalized)
        if target is not None:
            assert_recommendation_transition(recommendation.status, target)
            recommendation.status = target
        recommendation.outcome = {
            "verdict": normalized,
            "detail": detail or {},
            "at": moment.isoformat(),
            "recorded_by": recorded_by,
        }
        await session.flush()
        return outcome

    async def expire_stale(
        self,
        session: AsyncSession,
        *,
        now: Optional[datetime] = None,
        limit: int = 500,
    ) -> list[ReliabilityRecommendation]:
        """Expire open recommendations past their own deadline.

        An open card about a two-hour-old incident is not advice, it is noise; the
        row is kept with ``EXPIRED`` so the record shows it was raised and never
        acted on.
        """
        moment = now or datetime.now(timezone.utc)
        stmt = (
            select(ReliabilityRecommendation)
            .where(ReliabilityRecommendation.status == RecommendationStatus.OPEN)
            .where(ReliabilityRecommendation.expires_at.isnot(None))
            .where(ReliabilityRecommendation.expires_at <= moment)
            .limit(limit)
        )
        expired: list[ReliabilityRecommendation] = []
        for row in (await session.scalars(stmt)).all():
            row.status = RecommendationStatus.EXPIRED
            expired.append(row)
        if expired:
            await session.flush()
        return expired


#: Recommendation types whose implied action is reversible without a new change.
_REVERSIBLE_TYPES: frozenset[RecommendationType] = frozenset(
    {
        RecommendationType.INVESTIGATE_COMPONENT,
        RecommendationType.INVESTIGATE_DEPENDENCY,
        RecommendationType.REVIEW_RECENT_CHANGE,
        RecommendationType.REVIEW_REMEDIATION,
        RecommendationType.RUN_REPRODUCTION,
        RecommendationType.CONSIDER_RESTART,
        RecommendationType.REVIEW_CAPACITY,
    }
)


def _recommendation_for_action(action: str) -> Optional[RecommendationType]:
    mapping = {
        "restart_service": RecommendationType.CONSIDER_RESTART,
        "restart_instance": RecommendationType.CONSIDER_RESTART,
        "rollback_deployment": RecommendationType.CONSIDER_ROLLBACK,
        "rollback_configuration": RecommendationType.CONSIDER_ROLLBACK,
        "route_traffic_to_healthy_instance": RecommendationType.CONSIDER_TRAFFIC_SHIFT,
        "scale_service_within_limit": RecommendationType.REVIEW_CAPACITY,
    }
    return mapping.get(action.lower())


def _action_tallies(
    retrieval: RetrievalResult,
) -> tuple[dict[str, int], dict[str, int]]:
    """Counts per action across comparable episodes, and their successes."""
    counts: dict[str, int] = {}
    successes: dict[str, int] = {}
    for match in retrieval.matches:
        resolution = match.resolution or {}
        for action in resolution.get("action_types") or []:
            counts[action] = counts.get(action, 0) + 1
            if _match_succeeded(match):
                successes[action] = successes.get(action, 0) + 1
    return counts, successes


def _match_succeeded(match: Any) -> bool:
    resolution = match.resolution or {}
    if resolution.get("rollback_performed"):
        return False
    if resolution.get("outcome") == "effective":
        return True
    if match.outcome in ("effective", "patch_verified"):
        return True
    return False


def _confidence_for(
    sample: int, successes: int, settings: Settings
) -> KnowledgeConfidence:
    """Bucket the historical evidence behind one recommendation (§34)."""
    if sample < settings.INTELLIGENCE_MIN_SAMPLES_CANDIDATE:
        return KnowledgeConfidence.UNKNOWN
    ratio = successes / sample if sample else 0.0
    if sample >= settings.INTELLIGENCE_MIN_SAMPLES_HIGH_CONFIDENCE and ratio >= 0.8:
        return KnowledgeConfidence.HIGH
    if sample >= settings.INTELLIGENCE_MIN_SAMPLES_VALIDATION and ratio >= 0.6:
        return KnowledgeConfidence.MEDIUM
    return KnowledgeConfidence.LOW


def _confidence_score(confidence: KnowledgeConfidence) -> float:
    return {
        KnowledgeConfidence.UNKNOWN: 0.0,
        KnowledgeConfidence.LOW: 0.33,
        KnowledgeConfidence.MEDIUM: 0.66,
        KnowledgeConfidence.HIGH: 1.0,
    }.get(confidence, 0.0)


def _context_draft(
    *,
    incident: Any,
    evidence: dict[str, Any],
    knowledge_ids: Sequence[str],
    experience_ids: Sequence[str],
    historical: dict[str, Any],
    recommendation_type: RecommendationType,
    title: str,
    rationale: str,
) -> RecommendationDraft:
    return RecommendationDraft(
        project_id=incident.project_id,
        environment_id=incident.environment_id,
        component_id=incident.primary_component_id,
        incident_id=incident.id,
        recommendation_type=recommendation_type,
        title=title,
        rationale=rationale,
        current_evidence=evidence,
        knowledge_ids=list(knowledge_ids),
        experience_ids=list(experience_ids),
        limitations=[
            "This is context observed around the incident, not a demonstrated cause.",
        ],
        historical=historical,
        confidence=KnowledgeConfidence.LOW,
    )


__all__ = [
    "IMPLIED_ACTIONS",
    "RANKING_WEIGHTS",
    "RankedRecommendation",
    "RecommendationDraft",
    "ReliabilityRecommendationEngine",
]
