"""initial schema

Revision ID: 28c26487fe25
Revises:
Create Date: 2026-09-16 16:59:52.581080

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "28c26487fe25"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "PAUSED", "ARCHIVED", name="projectstatus"),
            nullable=False,
        ),
        sa.Column("repository_url", sa.String(length=512), nullable=True),
        sa.Column("repository_provider", sa.String(length=50), nullable=True),
        sa.Column("default_branch", sa.String(length=100), nullable=True),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_projects_slug"), "projects", ["slug"], unique=True)
    op.create_table(
        "code_repositories",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("repository_url", sa.String(length=512), nullable=False),
        sa.Column("default_branch", sa.String(length=100), nullable=False),
        sa.Column("connection_status", sa.String(length=50), nullable=False),
        sa.Column(
            "configuration",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_code_repositories_project_id"),
        "code_repositories",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "environments",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "environment_type",
            sa.Enum(
                "DEVELOPMENT",
                "TEST",
                "STAGING",
                "PRODUCTION",
                "CUSTOM",
                name="environmenttype",
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_environments_project_id"), "environments", ["project_id"], unique=False
    )
    op.create_table(
        "incidents",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("environment_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "severity",
            sa.Enum("LOW", "MEDIUM", "HIGH", "CRITICAL", name="incidentseverity"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "INVESTIGATING",
                "MITIGATED",
                "RESOLVED",
                "CLOSED",
                name="incidentstatus",
            ),
            nullable=False,
        ),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["environment_id"],
            ["environments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_incidents_detected_at"), "incidents", ["detected_at"], unique=False
    )
    op.create_index(
        op.f("ix_incidents_environment_id"),
        "incidents",
        ["environment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_incidents_project_id"), "incidents", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_incidents_severity"), "incidents", ["severity"], unique=False
    )
    op.create_index(op.f("ix_incidents_status"), "incidents", ["status"], unique=False)
    op.create_table(
        "system_components",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("environment_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "component_type",
            sa.Enum(
                "APPLICATION",
                "SERVICE",
                "WORKER",
                "DATABASE",
                "CACHE",
                "QUEUE",
                "EXTERNAL_API",
                "FRONTEND",
                "INFRASTRUCTURE",
                "UNKNOWN",
                name="componentcategory",
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "HEALTHY", "DEGRADED", "UNHEALTHY", "UNKNOWN", name="componentstatus"
            ),
            nullable=False,
        ),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["environment_id"],
            ["environments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_system_components_environment_id"),
        "system_components",
        ["environment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_system_components_project_id"),
        "system_components",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "traces",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("environment_id", sa.UUID(), nullable=True),
        sa.Column("trace_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Float(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("OK", "ERROR", "TIMEOUT", "UNKNOWN", name="tracestatus"),
            nullable=False,
        ),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["environment_id"],
            ["environments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_traces_environment_id"), "traces", ["environment_id"], unique=False
    )
    op.create_index(
        op.f("ix_traces_project_id"), "traces", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_traces_start_time"), "traces", ["start_time"], unique=False
    )
    op.create_index(op.f("ix_traces_trace_id"), "traces", ["trace_id"], unique=True)
    op.create_table(
        "component_dependencies",
        sa.Column("source_component_id", sa.UUID(), nullable=False),
        sa.Column("target_component_id", sa.UUID(), nullable=False),
        sa.Column(
            "dependency_type",
            sa.Enum(
                "HTTP",
                "DATABASE",
                "QUEUE",
                "CACHE",
                "RPC",
                "FILE",
                "EXTERNAL_API",
                "UNKNOWN",
                name="dependencytype",
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("discovered_at", sa.String(length=50), nullable=True),
        sa.Column("last_seen_at", sa.String(length=50), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_component_id"],
            ["system_components.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_component_id"],
            ["system_components.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_component_dependencies_source_component_id"),
        "component_dependencies",
        ["source_component_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_component_dependencies_target_component_id"),
        "component_dependencies",
        ["target_component_id"],
        unique=False,
    )
    op.create_table(
        "deployment_events",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("environment_id", sa.UUID(), nullable=True),
        sa.Column("component_id", sa.UUID(), nullable=True),
        sa.Column("deployment_id", sa.String(length=255), nullable=False),
        sa.Column("version", sa.String(length=100), nullable=True),
        sa.Column("commit_sha", sa.String(length=40), nullable=True),
        sa.Column("deployed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "STARTED",
                "SUCCESS",
                "FAILED",
                "ROLLED_BACK",
                "UNKNOWN",
                name="deploymentstatus",
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["system_components.id"],
        ),
        sa.ForeignKeyConstraint(
            ["environment_id"],
            ["environments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_deployment_events_component_id"),
        "deployment_events",
        ["component_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_deployment_events_deployed_at"),
        "deployment_events",
        ["deployed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_deployment_events_deployment_id"),
        "deployment_events",
        ["deployment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_deployment_events_environment_id"),
        "deployment_events",
        ["environment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_deployment_events_project_id"),
        "deployment_events",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "incident_evidence",
        sa.Column("incident_id", sa.UUID(), nullable=False),
        sa.Column(
            "evidence_type",
            sa.Enum(
                "LOG",
                "METRIC",
                "TRACE",
                "DEPLOYMENT",
                "CONFIGURATION_CHANGE",
                "CODE_CHANGE",
                "DEPENDENCY_CHANGE",
                "CUSTOM",
                name="evidencetype",
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.String(length=255), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("relevance_score", sa.Float(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_incident_evidence_incident_id"),
        "incident_evidence",
        ["incident_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_incident_evidence_timestamp"),
        "incident_evidence",
        ["timestamp"],
        unique=False,
    )
    op.create_table(
        "log_records",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("environment_id", sa.UUID(), nullable=True),
        sa.Column("component_id", sa.UUID(), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "level",
            sa.Enum(
                "DEBUG", "INFO", "WARN", "ERROR", "FATAL", "UNKNOWN", name="severity"
            ),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("service", sa.String(length=255), nullable=True),
        sa.Column("request_id", sa.String(length=255), nullable=True),
        sa.Column("trace_id", sa.String(length=255), nullable=True),
        sa.Column("span_id", sa.String(length=255), nullable=True),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column(
            "raw_payload",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["system_components.id"],
        ),
        sa.ForeignKeyConstraint(
            ["environment_id"],
            ["environments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_log_records_component_id"),
        "log_records",
        ["component_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_log_records_environment_id"),
        "log_records",
        ["environment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_log_records_level"), "log_records", ["level"], unique=False
    )
    op.create_index(
        op.f("ix_log_records_project_id"), "log_records", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_log_records_request_id"), "log_records", ["request_id"], unique=False
    )
    op.create_index(
        op.f("ix_log_records_service"), "log_records", ["service"], unique=False
    )
    op.create_index(
        op.f("ix_log_records_timestamp"), "log_records", ["timestamp"], unique=False
    )
    op.create_index(
        op.f("ix_log_records_trace_id"), "log_records", ["trace_id"], unique=False
    )
    op.create_table(
        "metric_records",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("environment_id", sa.UUID(), nullable=True),
        sa.Column("component_id", sa.UUID(), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("metric_name", sa.String(length=255), nullable=False),
        sa.Column(
            "metric_type",
            sa.Enum(
                "COUNTER", "GAUGE", "HISTOGRAM", "SUMMARY", "UNKNOWN", name="metrictype"
            ),
            nullable=False,
        ),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(length=50), nullable=True),
        sa.Column(
            "labels",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["system_components.id"],
        ),
        sa.ForeignKeyConstraint(
            ["environment_id"],
            ["environments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_metric_records_component_id"),
        "metric_records",
        ["component_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metric_records_environment_id"),
        "metric_records",
        ["environment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metric_records_metric_name"),
        "metric_records",
        ["metric_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metric_records_project_id"),
        "metric_records",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metric_records_timestamp"),
        "metric_records",
        ["timestamp"],
        unique=False,
    )
    op.create_table(
        "observability_events",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("environment_id", sa.UUID(), nullable=True),
        sa.Column("component_id", sa.UUID(), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=255), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "LOG",
                "METRIC",
                "TRACE",
                "DEPLOYMENT",
                "CONFIGURATION_CHANGE",
                "HEALTH_CHECK",
                "SYSTEM_EVENT",
                name="eventtype",
            ),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum(
                "DEBUG", "INFO", "WARN", "ERROR", "FATAL", "UNKNOWN", name="severity"
            ),
            nullable=True,
        ),
        sa.Column(
            "payload",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("request_id", sa.String(length=255), nullable=True),
        sa.Column("trace_id", sa.String(length=255), nullable=True),
        sa.Column("span_id", sa.String(length=255), nullable=True),
        sa.Column("deployment_id", sa.String(length=36), nullable=True),
        sa.Column("incident_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["system_components.id"],
        ),
        sa.ForeignKeyConstraint(
            ["environment_id"],
            ["environments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_observability_events_component_id"),
        "observability_events",
        ["component_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_observability_events_deployment_id"),
        "observability_events",
        ["deployment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_observability_events_environment_id"),
        "observability_events",
        ["environment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_observability_events_event_type"),
        "observability_events",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_observability_events_incident_id"),
        "observability_events",
        ["incident_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_observability_events_project_id"),
        "observability_events",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_observability_events_request_id"),
        "observability_events",
        ["request_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_observability_events_severity"),
        "observability_events",
        ["severity"],
        unique=False,
    )
    op.create_index(
        op.f("ix_observability_events_timestamp"),
        "observability_events",
        ["timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_observability_events_trace_id"),
        "observability_events",
        ["trace_id"],
        unique=False,
    )
    op.create_table(
        "spans",
        sa.Column("trace_id", sa.String(length=255), nullable=False),
        sa.Column("span_id", sa.String(length=255), nullable=False),
        sa.Column("parent_span_id", sa.String(length=255), nullable=True),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("component_id", sa.UUID(), nullable=True),
        sa.Column("operation", sa.String(length=255), nullable=True),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Float(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("OK", "ERROR", "TIMEOUT", "UNKNOWN", name="tracestatus"),
            nullable=False,
        ),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["system_components.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_spans_component_id"), "spans", ["component_id"], unique=False
    )
    op.create_index(
        op.f("ix_spans_parent_span_id"), "spans", ["parent_span_id"], unique=False
    )
    op.create_index(op.f("ix_spans_project_id"), "spans", ["project_id"], unique=False)
    op.create_index(op.f("ix_spans_span_id"), "spans", ["span_id"], unique=True)
    op.create_index(op.f("ix_spans_start_time"), "spans", ["start_time"], unique=False)
    op.create_index(op.f("ix_spans_trace_id"), "spans", ["trace_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_spans_trace_id"), table_name="spans")
    op.drop_index(op.f("ix_spans_start_time"), table_name="spans")
    op.drop_index(op.f("ix_spans_span_id"), table_name="spans")
    op.drop_index(op.f("ix_spans_project_id"), table_name="spans")
    op.drop_index(op.f("ix_spans_parent_span_id"), table_name="spans")
    op.drop_index(op.f("ix_spans_component_id"), table_name="spans")
    op.drop_table("spans")
    op.drop_index(
        op.f("ix_observability_events_trace_id"), table_name="observability_events"
    )
    op.drop_index(
        op.f("ix_observability_events_timestamp"), table_name="observability_events"
    )
    op.drop_index(
        op.f("ix_observability_events_severity"), table_name="observability_events"
    )
    op.drop_index(
        op.f("ix_observability_events_request_id"), table_name="observability_events"
    )
    op.drop_index(
        op.f("ix_observability_events_project_id"), table_name="observability_events"
    )
    op.drop_index(
        op.f("ix_observability_events_incident_id"), table_name="observability_events"
    )
    op.drop_index(
        op.f("ix_observability_events_event_type"), table_name="observability_events"
    )
    op.drop_index(
        op.f("ix_observability_events_environment_id"),
        table_name="observability_events",
    )
    op.drop_index(
        op.f("ix_observability_events_deployment_id"), table_name="observability_events"
    )
    op.drop_index(
        op.f("ix_observability_events_component_id"), table_name="observability_events"
    )
    op.drop_table("observability_events")
    op.drop_index(op.f("ix_metric_records_timestamp"), table_name="metric_records")
    op.drop_index(op.f("ix_metric_records_project_id"), table_name="metric_records")
    op.drop_index(op.f("ix_metric_records_metric_name"), table_name="metric_records")
    op.drop_index(op.f("ix_metric_records_environment_id"), table_name="metric_records")
    op.drop_index(op.f("ix_metric_records_component_id"), table_name="metric_records")
    op.drop_table("metric_records")
    op.drop_index(op.f("ix_log_records_trace_id"), table_name="log_records")
    op.drop_index(op.f("ix_log_records_timestamp"), table_name="log_records")
    op.drop_index(op.f("ix_log_records_service"), table_name="log_records")
    op.drop_index(op.f("ix_log_records_request_id"), table_name="log_records")
    op.drop_index(op.f("ix_log_records_project_id"), table_name="log_records")
    op.drop_index(op.f("ix_log_records_level"), table_name="log_records")
    op.drop_index(op.f("ix_log_records_environment_id"), table_name="log_records")
    op.drop_index(op.f("ix_log_records_component_id"), table_name="log_records")
    op.drop_table("log_records")
    op.drop_index(
        op.f("ix_incident_evidence_timestamp"), table_name="incident_evidence"
    )
    op.drop_index(
        op.f("ix_incident_evidence_incident_id"), table_name="incident_evidence"
    )
    op.drop_table("incident_evidence")
    op.drop_index(
        op.f("ix_deployment_events_project_id"), table_name="deployment_events"
    )
    op.drop_index(
        op.f("ix_deployment_events_environment_id"), table_name="deployment_events"
    )
    op.drop_index(
        op.f("ix_deployment_events_deployment_id"), table_name="deployment_events"
    )
    op.drop_index(
        op.f("ix_deployment_events_deployed_at"), table_name="deployment_events"
    )
    op.drop_index(
        op.f("ix_deployment_events_component_id"), table_name="deployment_events"
    )
    op.drop_table("deployment_events")
    op.drop_index(
        op.f("ix_component_dependencies_target_component_id"),
        table_name="component_dependencies",
    )
    op.drop_index(
        op.f("ix_component_dependencies_source_component_id"),
        table_name="component_dependencies",
    )
    op.drop_table("component_dependencies")
    op.drop_index(op.f("ix_traces_trace_id"), table_name="traces")
    op.drop_index(op.f("ix_traces_start_time"), table_name="traces")
    op.drop_index(op.f("ix_traces_project_id"), table_name="traces")
    op.drop_index(op.f("ix_traces_environment_id"), table_name="traces")
    op.drop_table("traces")
    op.drop_index(
        op.f("ix_system_components_project_id"), table_name="system_components"
    )
    op.drop_index(
        op.f("ix_system_components_environment_id"), table_name="system_components"
    )
    op.drop_table("system_components")
    op.drop_index(op.f("ix_incidents_status"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_severity"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_project_id"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_environment_id"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_detected_at"), table_name="incidents")
    op.drop_table("incidents")
    op.drop_index(op.f("ix_environments_project_id"), table_name="environments")
    op.drop_table("environments")
    op.drop_index(
        op.f("ix_code_repositories_project_id"), table_name="code_repositories"
    )
    op.drop_table("code_repositories")
    op.drop_index(op.f("ix_projects_slug"), table_name="projects")
    op.drop_table("projects")
    # ### end Alembic commands ###
